version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:16rc1-alpine3.18
    env_file:
      - ./docker/postgres/.env
    volumes:
      - ./docker/postgres/dump:/var/lib/postgresql/data
      - ./docker/postgres/init/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - tabletki
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./docker/backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - tabletki

networks:
  tabletki:
    driver: bridge
